### ISSUE TITLE
not an element

### ISSUE THREAD

**Issue by aric87** [theperfectfuel/music-time-warp#3]
[Here](https://github.com/theperfectfuel/music-time-warp/blob/master/js/main.js#L7) you are using menuToggle as if it was a DOM element. But, your storing `$('#js-mobile-menu').unbind();` in the variable. Technically, this works but you should seperate the DOM element from the invocation of unbind()

**Comment by theperfectfuel** [comment]
This is library code coming from Bourbon, so leaving as is and closing issue.

Thanks.
